name: C/C++ CI

on:
  push:
    branches: [ "PDB-refactor" ]
  pull_request:
    branches: [ "PDB-refactor" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      working-directory: ./build/SFML/
      run: make OPENGL=STUB
